name: Pub to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install build twine
      - run: python -m build
      - name: Upload to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_KEY }}
        run: twine upload dist/* -u __token__ -p "$PYPI_API_TOKEN"
